config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :properties
  root to: 'properties#index'
  resources :webhook_endpoints
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/api/v1/graphql"
  end
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: { registrations: "registrations" }

  namespace :api do
    namespace :v1 do
      post '/webhooks', to: proc { [204, {}, []] }
      post '/graphql', to: 'graphql#execute'
    end
  end

  get 'health_check', to: 'health_checks#check'
  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: {subdomain: 'www'}
  # get '/:id', to: 'properties#show', as: 'property'
  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "home#robots", format: :text, as: :robots
end

app/controllers/webhook_endpoints_controller.rb
class WebhookEndpointsController < ApplicationController
  before_action :set_webhook_endpoint, only: [:show, :edit, :update, :destroy]

  # GET /webhook_endpoints
  def index
    @webhook_endpoints = WebhookEndpoint.all
  end

  # GET /webhook_endpoints/1
  def show
  end

  # GET /webhook_endpoints/new
  def new
    @webhook_endpoint = WebhookEndpoint.new
  end

  # GET /webhook_endpoints/1/edit
  def edit
  end

  # POST /webhook_endpoints
  def create
    if (res = WebhookEndpoints::Operations::Create.call(record_params: webhook_endpoint_params)).success?
      @webhook_endpoint = res.args[:record]
      binding.pry
      redirect_to @webhook_endpoint, notice: 'Webhook endpoint was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /webhook_endpoints/1
  def update
    if (res = WebhookEndpoints::Operations::Update.call(record_params: webhook_endpoint_params,
                                                        record: @webhook_endpoint)).success?
      @webhook_endpoint = res.args[:record]
      redirect_to @webhook_endpoint, notice: 'Webhook endpoint was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /webhook_endpoints/1
  def destroy
    WebhookEndpoints::Operations::Destroy.call(record: @webhook_endpoint)
    redirect_to webhook_endpoints_url, notice: 'Webhook endpoint was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_webhook_endpoint
    @webhook_endpoint = WebhookEndpoint.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def webhook_endpoint_params
    params.require(:webhook_endpoint).permit!
  end
end

app/views/webhook_endpoints/_form.html.slim
= form_for @webhook_endpoint do |f|
  - if @webhook_endpoint.errors.any?
    #error_explanation
      h2 = "#{pluralize(@webhook_endpoint.errors.count, "error")} prohibited this webhook_endpoint from being saved:"
      ul
        - @webhook_endpoint.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :subscriptions
    = f.text_field :subscriptions
  .field
    = f.label :enabled
    = f.check_box :enabled
  / .field
    / = f.label :user
  = f.hidden_field :user_id, value: current_user.id
  .actions = f.submit

app/views/webhook_endpoints/edit.html.slim
h1 Editing webhook_endpoint

== render 'form'

=> link_to 'Show', @webhook_endpoint
'|
=< link_to 'Back', webhook_endpoints_path

app/views/webhook_endpoints/index.html.slim
h1 Listing webhook_endpoints

table
  thead
    tr
      th Url
      th Subscriptions
      th Enabled
      th User
      th
      th
      th

  tbody
    - @webhook_endpoints.each do |webhook_endpoint|
      tr
        td = webhook_endpoint.url
        td = webhook_endpoint.subscriptions
        td = webhook_endpoint.enabled
        td = webhook_endpoint.user
        td = link_to 'Show', webhook_endpoint
        td = link_to 'Edit', edit_webhook_endpoint_path(webhook_endpoint)
        td = link_to 'Destroy', webhook_endpoint, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Webhook endpoint', new_webhook_endpoint_path

app/views/webhook_endpoints/new.html.slim
h1 New webhook_endpoint

== render 'form'

= link_to 'Back', webhook_endpoints_path

app/views/webhook_endpoints/show.html.slim
p#notice = notice

p
  strong Url:
  = @webhook_endpoint.url
p
  strong Subscriptions:
  = @webhook_endpoint.subscriptions
p
  strong Enabled:
  = @webhook_endpoint.enabled
p
  strong User:
  = @webhook_endpoint.user

=> link_to 'Edit', edit_webhook_endpoint_path(@webhook_endpoint)
'|
=< link_to 'Back', webhook_endpoints_path