config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :properties
  root to: 'properties#index'
  resources :webhook_endpoints
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/api/v1/graphql"
  end
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users, controllers: { registrations: "registrations" }

  namespace :api do
    namespace :v1 do
      post '/webhooks', to: proc { [204, {}, []] }
      post '/graphql', to: 'graphql#execute'
    end
  end

  get 'health_check', to: 'health_checks#check'
  match '(*any)', to: redirect(subdomain: ''), via: :all, constraints: {subdomain: 'www'}
  # get '/:id', to: 'properties#show', as: 'property'
  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "home#robots", format: :text, as: :robots
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[show edit update destroy]
  before_action :set_page_meta_tags, only: %i[index show new edit]

  def index
    @page_title = 'Listing properties'
    @properties = current_user.properties
  end

  def show
    @page_title = "Property - #{@property.name}"
  end

  def new
    @page_title = 'New property'
    @property = Property.new
  end

  def edit
    @page_title = "Edit #{@property.name}"
  end

  def create
    res = Properties::Operations::Create.call(record_params: property_params.merge!(user_id: current_user.id))
    @property = res.args[:record]
    if res.success?
      redirect_to @property, notice: 'Property was successfully created.'
    else
      render :new
    end
  end

  def update
    res = Properties::Operations::Update.call(record: @property, record_params: property_params)
    @property = res.args[:record]
    if res.success?
      redirect_to @property, notice: 'Property was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    Properties::Operations::Destroy.call(record: @property)
    redirect_to properties_url, notice: 'Property was successfully destroyed.'
  end

  private

  def set_page_meta_tags
    set_meta_tags title: @page_title, description: 'Member login page.', keywords: 'Site, Login, Members'
  end

  def set_property
    @property = Property.friendly.find(params[:id])
  end

  def property_params
    params.require(:property).permit!
  end
end

app/views/properties/_form.html.slim
= form_for @property do |f|
  - if @property.errors.any?
    #error_explanation
      h2 = "#{pluralize(@property.errors.count, "error")} prohibited this property from being saved:"
      ul
        - @property.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :notes
    = f.text_area :notes
  .field
    = f.label :photo
    = f.file_field :photo
  .actions = f.submit

app/views/properties/edit.html.slim
h1
  = title @page_title

== render 'form'

=> link_to 'Show', @property
'|
=< link_to 'Back', properties_path

app/views/properties/index.html.slim
h1
  = title @page_title

table
  thead
    tr
      th Name
      th Address
      th City
      th Notes
      th User
      th
      th
      th

  tbody
    - @properties.each do |property|
      tr
        td = property.name
        td = property.address
        td = property.city
        td = property.notes
        td = property.user.email
        td = link_to 'Show', property
        td = link_to 'Edit', edit_property_path(property)
        td = link_to 'Destroy', property, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Property', new_property_path

app/views/properties/new.html.slim
h1
  = title @page_title

== render 'form'

= link_to 'Back', properties_path

app/views/properties/show.html.slim
h1
  = title @page_title

p#notice = notice

p
  = image_tag(@property.photo, width: 200) if @property.photo.attached?
p
  strong Name:
  = @property.name
p
  strong Address:
  = @property.address
p
  strong City:
  = @property.city
p
  strong Notes:
  = @property.notes
p
  strong User:
  = @property.user.email

=> link_to 'Edit', edit_property_path(@property)
'|
=< link_to 'Back', properties_path